version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.8-jdk
      - image: circleci/postgres:12.2
        environment:
          POSTGRES_DB: ls_cosmos_core_test
          POSTGRES_PASSWORD: cosmosCore

    working_directory: ~/cosmos-core
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      SPRING_PROFILES_ACTIVE: tests

    steps:
      - checkout:
          path: ~/cosmos-core

      - restore_cache:
          keys:
            - cosmos-core-{{ checksum "build.gradle" }}
            - cosmos-core-

      - run: gradle test
      - save_cache:
          paths:
            - ~/.m2
          key: cosmos-core-{{ checksum "build.gradle" }}

      - store_test_results:
          path: ~/cosmos-core/build/test-results/test

      - run: gradle bootJar
      - store_artifacts:
          path: build/libs
          destination: cosmos-core
