version: 2
jobs:
  build:
    docker:
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: ls_cosmos_core_test

      - image: circleci/openjdk:11.0.8-jdk

    working_directory: ~/cosmos-core
    steps:
      - checkout
      - restore_cache:
          keys:
            - cosmos-core-{{ checksum "build.gradle" }}

      - run: gradlew clean
      - save_cache:
          paths:
            - ~/.m2
          key: cosmos-core-{{ checksum "build.gradle" }}

      - run: gradlew bootJar
      - store_artifacts:
          path: build/libs
          destination: cosmos-core
